version: '3'
services:
  web:
    build: .
    ports:
     - "5000:5000"
  client:
    build: ./client
    ports:
      - "8080:8080"
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example